import os

import modal
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, field_validator

MIN_WORDS = 40
MAX_WORDS = 5000

app = modal.App("aletheia-detector")

image = (
    modal.Image.debian_slim(python_version="3.12")
    .uv_pip_install(
        "torch",
        "transformers",
        "accelerate",
        "huggingface_hub",
        "fastapi",
        "numpy",
        "pydantic",
        "markdown",
        "beautifulsoup4",
    )
    .add_local_dir(".", remote_path="/root")
)

hf_cache = modal.Volume.from_name("aletheia-hf-cache", create_if_missing=True)

# Cheapest available GPUs, with fallback
GPU_CONFIG = ["T4", "L4"]


class DetectRequest(BaseModel):
    text: str
    models: list[str] | None = None

    @field_validator("text")
    @classmethod
    def _check_length(cls, v: str) -> str:
        words = len(v.split())
        if words < MIN_WORDS or words > MAX_WORDS:
            raise ValueError(
                f"Text has {words} words. Need {MIN_WORDS}-{MAX_WORDS} words "
                f"(word count is whitespace-split, approximate for CJK)."
            )
        return v


class DetectResponse(BaseModel):
    results: dict


@app.cls(
    image=image,
    gpu=GPU_CONFIG,
    volumes={"/hf-cache": hf_cache},
    timeout=600,
    scaledown_window=20 * 60,
    max_containers=1,
)
class DetectorService:
    @modal.enter()
    def load(self):
        os.environ["HF_HOME"] = "/hf-cache"

        import torch
        from detectors import (
            DesklibDetector,
            FakespotDetector,
            MageDetector,
            RadarDetector,
            SuperAnnotateDetector,
            SuperAnnotateLowFprDetector,
            SzegedDetector,
        )

        device = "cuda" if torch.cuda.is_available() else "cpu"
        self._device = device
        print(f"Using device: {device}")

        self.detectors = {
            d.name: d
            for d in [
                FakespotDetector(device),
                SzegedDetector(device),
                DesklibDetector(device),
                SuperAnnotateLowFprDetector(device),
                SuperAnnotateDetector(device),
                MageDetector(device),
                RadarDetector(device),
            ]
        }

        for detector in list(self.detectors.values()):
            print(f"Loading {detector.name}...")
            try:
                detector.load()
                print(f"{detector.name} ready.")
            except Exception as e:
                print(f"FAILED to load {detector.name}: {e}")
                del self.detectors[detector.name]

    @modal.method()
    def detect(self, text: str, model_names: list[str] | None = None) -> dict:
        names = model_names or list(self.detectors.keys())
        invalid = [n for n in names if n not in self.detectors]
        if invalid:
            raise ValueError(
                f"Unknown models: {invalid}. Available: {list(self.detectors.keys())}"
            )

        # Sequential execution to keep resource usage predictable on a cheap GPU
        results = {}
        for name in names:
            result = self.detectors[name].predict(text)
            results[name] = result.model_dump()
        return results

    @modal.asgi_app(requires_proxy_auth=True)
    def web(self):
        api = FastAPI(title="Aletheia Detector")

        @api.get("/health")
        async def health():
            return {
                "status": "ok",
                "available_models": list(self.detectors.keys()),
                "device": self._device,
            }

        @api.get("/models")
        async def list_models():
            return {
                "score_format": "P(AI) in [0,1]; >= 0.5 means AI Generated",
                "models": [
                    {
                        "name": d.name,
                        "description": d.description,
                        "window_tokens": d.max_tokens,
                    }
                    for d in self.detectors.values()
                ],
            }

        @api.post("/detect", response_model=DetectResponse)
        async def detect_endpoint(req: DetectRequest):
            try:
                names = req.models or list(self.detectors.keys())
                invalid = [n for n in names if n not in self.detectors]
                if invalid:
                    raise HTTPException(
                        status_code=400, detail=f"Unknown models: {invalid}"
                    )

                results = {}
                for name in names:
                    results[name] = self.detectors[name].predict(req.text).model_dump()
                return DetectResponse(results=results)
            except Exception as e:
                raise HTTPException(status_code=500, detail=str(e))

        return api


@app.local_entrypoint()
def main(
    text: str = "This is a test sentence generated by an AI model to demonstrate capabilities.",
    model: str = "fakespot",
):
    """Run a quick remote test against a single model."""
    print(f"Testing model: {model}")
    result = DetectorService().detect.remote(text, [model])
    print(f"Result: {result}")
